# Generated by Django 6.0.2 on 2026-04-16 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0007_tarea_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='duracion_estimada_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo estimado de trabajo en minutos.'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_planificada',
            field=models.DateField(blank=True, help_text='Día en que planeas trabajar esta tarea (si vacío, se usa la fecha de entrega).', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=8),
        ),
        migrations.CreateModel(
            name='PerfilCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_minutos_diario', models.PositiveIntegerField(default=360, help_text='Carga máxima planificable por día (ej. 360 = 6 h).')),
                ('advertencia_umbral_pct', models.PositiveSmallIntegerField(default=85, help_text='Porcentaje del límite a partir del cual se muestra aviso (no bloqueante).')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_carga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de carga',
                'verbose_name_plural': 'Perfiles de carga',
            },
        ),
    ]
