# Generated by Django 6.0.2 on 2026-04-16 01:13

import django.core.validators
from django.db import migrations, models


def cap_datos_limite_y_duracion(apps, schema_editor):
    PerfilCarga = apps.get_model("focusflow", "PerfilCarga")
    Tarea = apps.get_model("focusflow", "Tarea")
    for p in PerfilCarga.objects.all():
        v = p.limite_minutos_diario
        nuevo = max(30, min(360, v))
        if nuevo != v:
            p.limite_minutos_diario = nuevo
            p.save(update_fields=["limite_minutos_diario"])
    for t in Tarea.objects.all():
        v = t.duracion_estimada_minutos
        nuevo = max(15, min(360, v))
        if nuevo != v:
            t.duracion_estimada_minutos = nuevo
            t.save(update_fields=["duracion_estimada_minutos"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0008_tarea_duracion_estimada_minutos_and_more'),
    ]

    operations = [
        migrations.RunPython(cap_datos_limite_y_duracion, noop_reverse),
        migrations.AlterField(
            model_name='perfilcarga',
            name='limite_minutos_diario',
            field=models.PositiveIntegerField(default=360, help_text='Carga máxima planificable por día (30–360 min; máximo 6 h).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='duracion_estimada_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo estimado de trabajo en minutos (15–360; no más que 6 h).', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
